### ISSUE TITLE
Pretrained Weights Link

### ISSUE THREAD

**Issue by ShisuiUzumaki** [TongfeiLiu/LGPNet#1]
The pre-trained weights link has expired, could you share it again

**Comment by TongfeiLiu** [comment]
Thank you very much for your interest in our work. The sharing link of the pre-trained model will be updated in the next few days.

**Comment by TongfeiLiu** [comment]
You can try to get the pre-trained weights from the following link:

Link：https://pan.baidu.com/s/1M4hVkc7b4cxN6Yg1H58xgw
code：2580

Tongfei Liu
Xidian University
发件人: ***@***.***>
发送时间: 2022年8月29日 16:04
收件人: ***@***.***>
抄送: ***@***.***>
主题: [TongfeiLiu/LGPNet-for-building-CD] Pretrained Weights Link (Issue #1)


The pre-trained weights link has expired, could you share it again

―

**Comment by ShisuiUzumaki** [comment]
Even this link is not working

**Comment by TongfeiLiu** [comment]
Try the following links:
https://drive.google.com/drive/folders/1boNPE71ZVUAdbR9Du4d26gzcCnf7hxlh?usp=sharing

**Comment by ShisuiUzumaki** [comment]
> Try the following links: https://drive.google.com/drive/folders/1boNPE71ZVUAdbR9Du4d26gzcCnf7hxlh?usp=sharing

@TongfeiLiu Thank you!
